apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: blackduck-connector-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: This operator installs the Black Duck connector to your cluster & starts scanning pods.
  displayName: blackduck-connector-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - Security
  - Monitoring
  links:
  - name: Blackduck Connector Operator
    url: https://blackduck-connector-operator.domain
  maturity: alpha
  provider:
    name: Synopsys, Inc.
    url: https://www.synopsys.com
  version: 0.0.0
