# permissions for end users to view blackduckconnectors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: blackduckconnector-viewer-role
rules:
- apiGroups:
  - charts.synopsys.com
  resources:
  - blackduckconnectors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - charts.synopsys.com
  resources:
  - blackduckconnectors/status
  verbs:
  - get
